# Generated by Django 5.2.8 on 2026-02-14 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reputation', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='globalcustomerprofile',
            new_name='rep_last_order_idx',
            old_name='rep_glob_last_order_idx',
        ),
        migrations.RemoveField(
            model_name='globalcustomerprofile',
            name='total_orders_count',
        ),
        migrations.AddField(
            model_name='globalcustomerprofile',
            name='risk_level',
            field=models.CharField(choices=[('ELITE', 'Elite'), ('GOOD', 'Good'), ('NEUTRAL', 'Neutral'), ('RISKY', 'Risky'), ('BLACKLIST', 'Blacklist')], default='NEUTRAL', help_text='ELITE ≥80 | GOOD 60-79 | NEUTRAL 40-59 | RISKY 20-39 | BLACKLIST <20', max_length=16),
        ),
        migrations.AddField(
            model_name='globalcustomerprofile',
            name='total_orders',
            field=models.PositiveIntegerField(default=0, help_text='Total finalized orders (DELIVERED + RETURNED + CANCELED + NO_ANSWER)'),
        ),
        migrations.AddField(
            model_name='globalcustomerprofile',
            name='trust_score',
            field=models.FloatField(default=50.0, help_text='Trust score (0-100). Base 50 + (Delivered +10, Returned -10, No Answer -5, Canceled -2)'),
        ),
        migrations.AddIndex(
            model_name='globalcustomerprofile',
            index=models.Index(fields=['risk_level'], name='rep_risk_level_idx'),
        ),
    ]
