# Generated by Django 5.2.8 on 2026-02-20 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reputation', '0003_merge_20260214_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalcustomerprofile',
            name='risk_level',
            field=models.CharField(choices=[('ELITE', 'Elite'), ('GOOD', 'Good'), ('NEUTRAL', 'Neutral'), ('RISKY', 'Risky'), ('BLACKLIST', 'Blacklist')], default='NEUTRAL', max_length=16),
        ),
        migrations.AlterField(
            model_name='globalcustomerprofile',
            name='trust_score',
            field=models.FloatField(default=50.0, help_text='Trust score 0-100. Base 50 + Delivered*10 - Returned*10 - NoAnswer*5 - Canceled*2'),
        ),
    ]
