# Generated by Django 4.2.6 on 2025-06-06 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='externaltokenmodel',
            name='token_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
