# Generated by Django 4.2.6 on 2025-06-08 23:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('discount', '0002_externaltokenmodel_token_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='stuff_momber',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('order_created', 'Order Created'), ('order_updated', 'Order Updated'), ('order_deleted', 'Order Deleted'), ('user_created', 'User Created'), ('user_updated', 'User Updated'), ('user_deleted', 'User Deleted'), ('password_changed', 'Password Changed'), ('2fa_enabled', 'Two-Factor Auth Enabled'), ('2fa_disabled', 'Two-Factor Auth Disabled'), ('search_performed', 'Search Performed'), ('filter_applied', 'Filter Applied')], db_index=True, max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('active_time', models.TimeField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
