# Generated by Django 4.2.6 on 2025-06-10 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0003_customuser_stuff_momber_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('order_created', 'Order Created'), ('order_updated', 'Order Updated'), ('order_deleted', 'Order Deleted'), ('user_created', 'User Created'), ('user_updated', 'User Updated'), ('user_deleted', 'User Deleted'), ('product_filter', 'Product Filterd'), ('password_changed', 'Password Changed'), ('2fa_enabled', 'Two-Factor Auth Enabled'), ('2fa_disabled', 'Two-Factor Auth Disabled'), ('search_performed', 'Search Performed'), ('filter_applied', 'Filter Applied')], db_index=True, max_length=50),
        ),
    ]
