# Generated by Django 4.2.6 on 2025-06-11 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0005_products_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProductPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('viewer', 'مشاهد'), ('editor', 'محرر'), ('manager', 'مشرف')], default='viewer', max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_permissions', to='discount.products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'product')},
            },
        ),
    ]
