# Generated by Django 4.2.6 on 2025-06-11 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0006_userproductpermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='simpleorder',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='discount.products', verbose_name='المنتج المرتبط'),
        ),
    ]
