# Generated by Django 4.2.21 on 2025-06-21 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0007_simpleorder_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='project',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
