# Generated by Django 4.2.21 on 2025-06-22 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0011_order_product_price_order_product_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproductpermission',
            name='daily_order_limit',
            field=models.IntegerField(default=0),
        ),
    ]
