# Generated by Django 4.2.21 on 2025-06-22 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0012_userproductpermission_daily_order_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simpleorder',
            name='tracking_number',
            field=models.CharField(max_length=100, null=True, verbose_name='رقم التتبع'),
        ),
    ]
