# Generated by Django 4.2.21 on 2025-07-01 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0014_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='calls',
            field=models.IntegerField(default=0, verbose_name=' calls count'),
        ),
        migrations.AddField(
            model_name='lead',
            name='lead_inputs',
            field=models.JSONField(default=dict, verbose_name='lead inputs'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name=' created at'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='message',
            field=models.TextField(verbose_name='message'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='name',
            field=models.CharField(max_length=255, verbose_name=' client name'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='phone',
            field=models.CharField(max_length=20, verbose_name=' phone number'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(default='processing', max_length=20, verbose_name='status'),
        ),
    ]
