# Generated by Django 4.2.21 on 2025-07-07 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0015_lead_calls_lead_lead_inputs_alter_lead_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='simpleorder',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='السعر'),
        ),
    ]
