# Generated by Django 4.2.21 on 2025-08-09 12:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0016_simpleorder_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignVisit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('raw_phone', models.CharField(blank=True, max_length=64, null=True)),
                ('phone_normalized', models.CharField(db_index=True, max_length=32)),
                ('utm_campaign', models.CharField(blank=True, max_length=200, null=True)),
                ('utm_source', models.CharField(blank=True, max_length=200, null=True)),
                ('utm_medium', models.CharField(blank=True, max_length=200, null=True)),
                ('ad_id', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExternalOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(default='unknown', max_length=50)),
                ('external_order_id', models.CharField(db_index=True, max_length=200)),
                ('order_ref', models.CharField(blank=True, max_length=200, null=True)),
                ('raw_phone', models.CharField(blank=True, max_length=64, null=True)),
                ('phone_normalized', models.CharField(db_index=True, max_length=32)),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('tracking_number', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('created', 'created'), ('confirmed', 'confirmed'), ('shipped', 'shipped'), ('delivered', 'delivered'), ('cancelled', 'cancelled'), ('unknown', 'unknown')], default='unknown', max_length=30)),
                ('created_at', models.DateTimeField()),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('matched_visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='discount.campaignvisit')),
            ],
            options={
                'indexes': [models.Index(fields=['phone_normalized', 'created_at'], name='discount_ex_phone_n_39fd20_idx'), models.Index(fields=['external_order_id'], name='discount_ex_externa_33617c_idx'), models.Index(fields=['tracking_number'], name='discount_ex_trackin_c74d98_idx')],
            },
        ),
    ]
