# Generated by Django 4.2.21 on 2025-08-10 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0017_campaignvisit_externalorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignvisit',
            name='site_source_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
