# Generated by Django 4.2.21 on 2025-08-11 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0018_campaignvisit_site_source_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignvisit',
            name='ad_adset_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
