# Generated by Django 4.2.21 on 2025-08-14 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0019_campaignvisit_ad_adset_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
