# Generated by Django 4.2.21 on 2025-08-14 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0020_order_customer_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='simpleorder',
            name='customer_country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name=' coutry'),
        ),
    ]
