# Generated by Django 4.2.21 on 2025-08-16 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0021_simpleorder_customer_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPermissionSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_create_orders', models.BooleanField(default=False)),
                ('can_view_analytics', models.BooleanField(default=False)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permission_setting', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
