# Generated by Django 4.2.21 on 2025-08-17 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0022_userpermissionsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='history',
            field=models.JSONField(default=list, verbose_name='history'),
        ),
        migrations.AddField(
            model_name='lead',
            name='items',
            field=models.JSONField(default=dict, verbose_name='items'),
        ),
    ]
