# Generated by Django 4.2.21 on 2025-08-20 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0023_lead_history_lead_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='simpleorder',
            name='currency',
            field=models.CharField(blank=True, default='SAR', max_length=10, null=True, verbose_name='العملة'),
        ),
    ]
