# Generated by Django 4.2.21 on 2025-08-21 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0024_simpleorder_currency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaignvisit',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='campaignvisit',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaign_visits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='campaignvisit',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='campaignvisit',
            name='phone_normalized',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
        migrations.AddIndex(
            model_name='campaignvisit',
            index=models.Index(fields=['phone_normalized'], name='discount_ca_phone_n_ebd04c_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignvisit',
            index=models.Index(fields=['created_at'], name='discount_ca_created_fd59df_idx'),
        ),
    ]
