# Generated by Django 4.2.21 on 2025-08-21 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0025_alter_campaignvisit_options_campaignvisit_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScriptFlow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('api_key', models.CharField(max_length=128, unique=True)),
                ('allowed_domains', models.TextField(blank=True, help_text='Comma separated domains allowed (e.g. shop.com,myshop.com)')),
                ('config', models.JSONField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='script_flows', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='campaignvisit',
            name='flow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='discount.scriptflow'),
        ),
    ]
