# Generated by Django 4.2.21 on 2025-08-21 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0026_scriptflow_campaignvisit_flow'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignvisit',
            name='visit_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
