# Generated by Django 4.2.21 on 2025-08-21 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0027_campaignvisit_visit_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='scriptflow',
            name='script',
            field=models.TextField(blank=True, null=True),
        ),
    ]
