# Generated by Django 4.2.21 on 2025-08-25 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0029_customuser_email_verification_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdCreative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creative_id', models.CharField(max_length=128, unique=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('image_hash', models.CharField(blank=True, max_length=128, null=True)),
                ('video_id', models.CharField(blank=True, max_length=128, null=True)),
                ('video_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_id', models.CharField(max_length=128, unique=True)),
                ('page_id', models.CharField(blank=True, max_length=64, null=True)),
                ('page_name', models.CharField(blank=True, max_length=255, null=True)),
                ('ad_snapshot_url', models.URLField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, max_length=8, null=True)),
                ('ad_delivery_start_time', models.DateTimeField(blank=True, null=True)),
                ('ad_delivery_stop_time', models.DateTimeField(blank=True, null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('raw_json', models.JSONField(blank=True, null=True)),
                ('creative', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='discount.adcreative')),
            ],
        ),
    ]
