# Generated by Django 5.2.6 on 2025-09-18 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0030_adcreative_adarchive'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertiser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_id', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('domain', models.CharField(blank=True, max_length=255, null=True)),
                ('page_url', models.URLField(blank=True, null=True)),
                ('ad_account', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, unique=True)),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='CTA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='adarchive',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='adarchive',
            name='page_id',
        ),
        migrations.RemoveField(
            model_name='adarchive',
            name='page_name',
        ),
        migrations.AddField(
            model_name='adarchive',
            name='adsets_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adarchive',
            name='clicks',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adarchive',
            name='conversions',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adarchive',
            name='cpa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='adarchive',
            name='cpc',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='adarchive',
            name='ctr',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adarchive',
            name='impressions',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adarchive',
            name='landing_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adarchive',
            name='platform',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='adarchive',
            name='roas',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adarchive',
            name='spend',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='adarchive',
            name='status',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='adcreative',
            name='aspect_ratio',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='adcreative',
            name='duration_seconds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adcreative',
            name='is_video',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adcreative',
            name='thumbnail_url',
            field=models.CharField(blank=True, max_length=768, null=True),
        ),
        migrations.AddField(
            model_name='adarchive',
            name='advertiser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='discount.advertiser'),
        ),
        migrations.AddField(
            model_name='adarchive',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='discount.country'),
        ),
        migrations.AddField(
            model_name='adarchive',
            name='ctas',
            field=models.ManyToManyField(blank=True, to='discount.cta'),
        ),
        migrations.CreateModel(
            name='MetricSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField(db_index=True)),
                ('impressions', models.BigIntegerField(blank=True, null=True)),
                ('spend', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('clicks', models.BigIntegerField(blank=True, null=True)),
                ('conversions', models.IntegerField(blank=True, null=True)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='discount.adarchive')),
            ],
        ),
        migrations.AddField(
            model_name='adarchive',
            name='tags',
            field=models.ManyToManyField(blank=True, to='discount.tag'),
        ),
        migrations.AddIndex(
            model_name='adarchive',
            index=models.Index(fields=['platform'], name='discount_ad_platfor_dc345b_idx'),
        ),
        migrations.AddIndex(
            model_name='adarchive',
            index=models.Index(fields=['country'], name='discount_ad_country_1fbc48_idx'),
        ),
        migrations.AddIndex(
            model_name='adarchive',
            index=models.Index(fields=['status'], name='discount_ad_status_1d33a5_idx'),
        ),
        migrations.AddIndex(
            model_name='adarchive',
            index=models.Index(fields=['ad_delivery_start_time'], name='discount_ad_ad_deli_d4c6bb_idx'),
        ),
        migrations.AddIndex(
            model_name='adarchive',
            index=models.Index(fields=['ad_delivery_stop_time'], name='discount_ad_ad_deli_8df7ca_idx'),
        ),
        migrations.AddIndex(
            model_name='adarchive',
            index=models.Index(fields=['spend'], name='discount_ad_spend_c51a41_idx'),
        ),
        migrations.AddIndex(
            model_name='adarchive',
            index=models.Index(fields=['impressions'], name='discount_ad_impress_979d41_idx'),
        ),
        migrations.AddIndex(
            model_name='metricsnapshot',
            index=models.Index(fields=['snapshot_date'], name='discount_me_snapsho_f46825_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='metricsnapshot',
            unique_together={('ad', 'snapshot_date')},
        ),
    ]
