# Generated by Django 5.2.6 on 2025-09-19 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0031_advertiser_country_cta_tag_remove_adarchive_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertiser',
            name='page_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
