# Generated by Django 5.2.6 on 2025-09-19 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0032_advertiser_page_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertiser',
            name='page_name',
        ),
        migrations.AddField(
            model_name='adarchive',
            name='page_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
