# Generated by Django 5.2.6 on 2025-09-19 20:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0033_remove_advertiser_page_name_adarchive_page_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSavedAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_id', models.CharField(max_length=128)),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_ads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
