# Generated by Django 5.2.6 on 2025-11-09 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0036_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
