# Generated by Django 5.2.6 on 2025-11-09 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0037_message_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
