# Generated by Django 5.2.6 on 2025-11-09 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0038_message_created_at_message_is_read_message_read_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='media_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='media_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='media_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
