# Generated by Django 5.2.6 on 2025-11-09 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0039_message_media_id_message_media_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='media_url',
        ),
        migrations.AddField(
            model_name='message',
            name='media_file',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='message',
            name='media_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='media_type',
            field=models.CharField(blank=True, choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio')], max_length=20, null=True),
        ),
    ]
