# Generated by Django 5.2.6 on 2025-11-10 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0040_remove_message_media_url_message_media_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('language', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('updated', models.CharField(blank=True, max_length=50, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('footer', models.TextField(blank=True, null=True)),
                ('header_type', models.CharField(blank=True, max_length=50, null=True)),
                ('header_text', models.CharField(blank=True, max_length=255, null=True)),
                ('header_image', models.FileField(blank=True, null=True, upload_to='headers/')),
                ('header_video', models.FileField(blank=True, null=True, upload_to='headers/')),
                ('header_audio', models.FileField(blank=True, null=True, upload_to='headers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
