# Generated by Django 5.2.6 on 2025-11-11 19:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0042_flow'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger', models.CharField(help_text='النص أو النمط الذي نطابقه', max_length=255)),
                ('match_type', models.CharField(choices=[('exact', 'Exact'), ('contains', 'Contains'), ('starts_with', 'Starts with'), ('regex', 'Regex')], default='contains', help_text='طريقة مطابقة النص الوارد', max_length=20)),
                ('response_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('audio', 'Audio'), ('video', 'Video')], default='text', help_text='نوع الرد الذي سيُرسل', max_length=12)),
                ('response_text', models.TextField(blank=True, help_text='نص الرد (إذا كان نوع الرد نص)')),
                ('media_file', models.FileField(blank=True, help_text='ملف وسائط يُستخدم في الرد إذا تطلب الأمر', null=True, upload_to='autoreply_media/')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AutoReply',
                'verbose_name_plural': 'AutoReplies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='flow',
            options={'ordering': ['-created_at'], 'verbose_name': 'Flow', 'verbose_name_plural': 'Flows'},
        ),
        migrations.AddField(
            model_name='flow',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='flow',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='flow',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='flow',
            name='flow_data',
            field=models.JSONField(blank=True, default=dict, help_text='JSON config for the flow (nodes, connections, steps...)'),
        ),
        migrations.AlterField(
            model_name='flow',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
