# Generated by Django 5.2.6 on 2025-11-12 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0043_autoreply_alter_flow_options_flow_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flow',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
