# Generated by Django 5.2.6 on 2025-11-12 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0044_flow_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_id',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
