# Generated by Django 5.2.6 on 2025-11-12 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0045_message_message_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlowExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('current_node', models.CharField(blank=True, max_length=100, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('session_data', models.JSONField(blank=True, default=dict, help_text='بيانات الجلسة والمتغيرات')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='autoreply',
            options={'ordering': ['-priority', '-created_at'], 'verbose_name': 'AutoReply', 'verbose_name_plural': 'AutoReplies'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='template',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='flow',
            name='count',
        ),
        migrations.AddField(
            model_name='autoreply',
            name='delay',
            field=models.IntegerField(default=0, help_text='تأخير الإرسال بالثواني'),
        ),
        migrations.AddField(
            model_name='autoreply',
            name='last_used',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='autoreply',
            name='priority',
            field=models.IntegerField(default=0, help_text='الأولوية (رقم أعلى = أولوية أعلى)'),
        ),
        migrations.AddField(
            model_name='autoreply',
            name='usage_count',
            field=models.IntegerField(default=0, help_text='عدد مرات استخدام هذه القاعدة'),
        ),
        migrations.AddField(
            model_name='flow',
            name='description',
            field=models.TextField(blank=True, help_text='وصف التدفق'),
        ),
        migrations.AddField(
            model_name='flow',
            name='is_template',
            field=models.BooleanField(default=False, help_text='هل هذا التدفق قالب يمكن إعادة استخدامه؟'),
        ),
        migrations.AddField(
            model_name='flow',
            name='last_used',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flow',
            name='success_count',
            field=models.IntegerField(default=0, help_text='عدد المرات التي أنهى فيها المستخدم التدفق'),
        ),
        migrations.AddField(
            model_name='flow',
            name='trigger_keywords',
            field=models.TextField(blank=True, help_text='كلمات مفتاحية لتفعيل التدفق (مفصولة بفاصلة)'),
        ),
        migrations.AddField(
            model_name='flow',
            name='usage_count',
            field=models.IntegerField(default=0, help_text='عدد مرات استخدام هذا التدفق'),
        ),
        migrations.AddField(
            model_name='flow',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed')], default='sent', max_length=20),
        ),
        migrations.AddField(
            model_name='message',
            name='status_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='template',
            name='components',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='template',
            name='template_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='template',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='autoreply',
            name='response_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('audio', 'Audio'), ('video', 'Video'), ('document', 'Document')], default='text', help_text='نوع الرد الذي سيُرسل', max_length=12),
        ),
        migrations.AlterField(
            model_name='message',
            name='media_type',
            field=models.CharField(blank=True, choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('document', 'Document')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='template',
            name='header_audio',
            field=models.FileField(blank=True, null=True, upload_to='templates/headers/'),
        ),
        migrations.AlterField(
            model_name='template',
            name='header_image',
            field=models.FileField(blank=True, null=True, upload_to='templates/headers/'),
        ),
        migrations.AlterField(
            model_name='template',
            name='header_video',
            field=models.FileField(blank=True, null=True, upload_to='templates/headers/'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', 'timestamp'], name='discount_me_sender_c8d263_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['message_id'], name='discount_me_message_668fe8_idx'),
        ),
        migrations.AddField(
            model_name='flowexecution',
            name='flow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='discount.flow'),
        ),
        migrations.AlterUniqueTogether(
            name='flowexecution',
            unique_together={('flow', 'phone_number')},
        ),
    ]
