# Generated by Django 5.2.6 on 2025-11-14 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0046_flowexecution_alter_autoreply_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flow',
            options={},
        ),
        migrations.RemoveField(
            model_name='flow',
            name='flow_data',
        ),
        migrations.RemoveField(
            model_name='flow',
            name='is_template',
        ),
        migrations.RemoveField(
            model_name='flow',
            name='version',
        ),
        migrations.AlterField(
            model_name='flow',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='flow',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flow',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_type', models.CharField(choices=[('text', 'Text Message'), ('media', 'Media Message'), ('mixed', 'Text + Media'), ('condition', 'Condition')], max_length=20)),
                ('position_x', models.FloatField(default=0)),
                ('position_y', models.FloatField(default=0)),
                ('content_text', models.TextField(blank=True, null=True)),
                ('content_media_url', models.URLField(blank=True, null=True)),
                ('delay', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='discount.flow')),
            ],
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(blank=True, max_length=255, null=True)),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='discount.flow')),
                ('from_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing', to='discount.node')),
                ('to_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming', to='discount.node')),
            ],
        ),
        migrations.DeleteModel(
            name='FlowExecution',
        ),
    ]
