# Generated by Django 5.2.6 on 2025-11-14 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0047_alter_flow_options_remove_flow_flow_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connection',
            name='condition',
        ),
        migrations.AddField(
            model_name='connection',
            name='data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='flow',
            name='start_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='start_flows', to='discount.node'),
        ),
        migrations.AddField(
            model_name='node',
            name='node_id',
            field=models.CharField(default=23, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='connection',
            name='from_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_connections', to='discount.node'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='to_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_connections', to='discount.node'),
        ),
    ]
