# Generated by Django 5.2.6 on 2025-11-14 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0048_remove_connection_condition_connection_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flow',
            name='config',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
