# Generated by Django 5.2.6 on 2025-11-17 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0049_flow_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='media_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
