# Generated by Django 5.2.6 on 2025-11-17 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0050_message_media_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('flow_started', models.BooleanField(default=False)),
                ('last_interaction', models.DateTimeField(auto_now=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='contacts/')),
            ],
        ),
    ]
