# Generated by Django 5.2.6 on 2025-11-21 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0051_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='template',
            old_name='updated',
            new_name='approval_status',
        ),
        migrations.AddField(
            model_name='template',
            name='buttons',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='template',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='template',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='template',
            name='last_used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='template',
            name='namespace',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='template',
            name='provider',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='template',
            name='sample_values',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='template',
            name='times_used',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='template',
            name='variables',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='template',
            name='variables_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='template',
            name='version',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
