# Generated by Django 5.2.6 on 2025-11-22 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0052_rename_updated_template_approval_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='media_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
