# Generated by Django 5.2.6 on 2025-11-22 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0053_node_media_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='node_type',
            field=models.CharField(max_length=30),
        ),
    ]
