# Generated by Django 5.2.6 on 2025-11-24 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0054_alter_node_node_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='flow',
            name='trigger_on_start',
            field=models.BooleanField(default=False, help_text='تفعيل هذا التدفق تلقائياً عند بداية المحادثة'),
        ),
    ]
