# Generated by Django 5.2.6 on 2025-11-25 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0055_flow_trigger_on_start'),
    ]

    operations = [
        migrations.CreateModel(
            name='groupchat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=333, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GroupMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=300)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('Group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chate_messages', to='discount.groupchat')),
                ('auther', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
