# Generated by Django 5.2.8 on 2025-11-29 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0056_groupchat_groupmessages'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='مثلاً: خدمة العملاء', max_length=100)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('phone_number_id', models.CharField(max_length=100, unique=True)),
                ('business_account_id', models.CharField(blank=True, max_length=100, null=True)),
                ('access_token', models.TextField(help_text='التوكن الدائم الخاص بهذا الرقم')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_agents', models.ManyToManyField(blank=True, related_name='channels', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='discount.whatsappchannel'),
        ),
    ]
