# Generated by Django 5.2.8 on 2025-11-29 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0057_whatsappchannel_message_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappchannel',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='المستخدم الذي أنشأ هذه القناة', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_channels', to=settings.AUTH_USER_MODEL, verbose_name='المالك'),
        ),
    ]
