# Generated by Django 5.2.8 on 2025-11-30 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0059_contact_channel_contact_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='flow',
            name='channel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='discount.whatsappchannel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flow',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
