# Generated by Django 5.2.8 on 2025-11-30 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0060_flow_channel_flow_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='channel',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='discount.whatsappchannel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='template',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
