# Generated by Django 5.2.8 on 2025-11-30 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0061_template_channel_template_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappchannel',
            name='api_version',
            field=models.CharField(default='v22.0', max_length=10),
        ),
    ]
