# Generated by Django 5.2.8 on 2025-12-02 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0063_order_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='discount.customuser'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discount.customuser'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='team_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='discount.customuser'),
        ),
        migrations.AlterField(
            model_name='externaltokenmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_tokens', to='discount.customuser'),
        ),
        migrations.AlterField(
            model_name='flow',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discount.customuser'),
        ),
        migrations.AlterField(
            model_name='groupmessages',
            name='auther',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discount.customuser'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='discount.customuser'),
        ),
        migrations.AlterField(
            model_name='products',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Products', to='discount.customuser'),
        ),
        migrations.AlterField(
            model_name='userproductpermission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_permissions', to='discount.customuser'),
        ),
        migrations.AlterField(
            model_name='whatsappchannel',
            name='assigned_agents',
            field=models.ManyToManyField(blank=True, related_name='channels', to='discount.customuser'),
        ),
        migrations.AlterField(
            model_name='whatsappchannel',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='المستخدم الذي أنشأ هذه القناة', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_channels', to='discount.customuser', verbose_name='المالك'),
        ),
    ]
