# Generated by Django 5.2.8 on 2025-12-05 20:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0064_alter_activity_user_alter_contact_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='simpleorder',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='simple_orders', to=settings.AUTH_USER_MODEL, verbose_name='الموظف المسؤول'),
        ),
        migrations.AddField(
            model_name='simpleorder',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='simple_orders', to='discount.whatsappchannel'),
        ),
    ]
