# Generated by Django 5.2.8 on 2025-12-08 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0065_simpleorder_agent_simpleorder_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='teaminvitation',
            name='channels',
            field=models.ManyToManyField(blank=True, related_name='invitations', to='discount.whatsappchannel'),
        ),
    ]
