# Generated by Django 5.2.8 on 2025-12-09 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0066_teaminvitation_channels'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='assigned_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_chats', to=settings.AUTH_USER_MODEL, verbose_name='الموظف المسؤول'),
        ),
    ]
