# Generated by Django 5.2.8 on 2025-12-09 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0067_contact_assigned_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_internal',
            field=models.BooleanField(default=False, help_text='إذا كانت True، لا تظهر للعميل ولا ترسل للواتساب'),
        ),
        migrations.AddField(
            model_name='message',
            name='type',
            field=models.CharField(default='text', max_length=50),
        ),
    ]
