# Generated by Django 5.2.8 on 2025-12-10 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0069_pipelinestage_contact_pipeline_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='pipeline_stage',
            field=models.CharField(choices=[('new', '🆕 New Chat'), ('interested', '🔥 Interested'), ('follow_up', '📅 Follow Up'), ('closed', '✅ Closed / Won'), ('rejected', '❌ Not Interested')], default='new', max_length=20, verbose_name='مرحلة العميل'),
        ),
        migrations.DeleteModel(
            name='PipelineStage',
        ),
    ]
