# Generated by Django 5.2.8 on 2025-12-11 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0071_tags_contact_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codproduct',
            name='country',
            field=models.CharField(blank=True, max_length=600),
        ),
        migrations.AlterField(
            model_name='codproduct',
            name='name',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='codproduct',
            name='project',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='codproduct',
            name='sku',
            field=models.CharField(blank=True, max_length=600, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='gift_chosen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chosen_gift', to='discount.codproduct'),
        ),
    ]
