# Generated by Django 5.2.8 on 2025-12-11 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0072_alter_codproduct_country_alter_codproduct_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codproduct',
            name='image_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
