# Generated by Django 5.2.8 on 2025-12-11 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0073_alter_codproduct_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simpleorder',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent', to=settings.AUTH_USER_MODEL, verbose_name='الموظف المسؤول'),
        ),
    ]
