# Generated by Django 5.2.8 on 2025-12-11 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0075_alter_simpleorder_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='simpleorder',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
    ]
