# Generated by Django 5.2.8 on 2025-12-13 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0076_simpleorder_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
