# Generated by Django 5.2.8 on 2025-12-16 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0077_alter_message_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
