# Generated by Django 5.2.8 on 2025-12-16 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0078_contact_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_seen',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
