# Generated by Django 5.2.8 on 2025-12-18 23:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0080_message_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CannedResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortcut', models.CharField(help_text='الكلمة التي ستظهر في القائمة بعد /', max_length=50)),
                ('message', models.TextField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=20, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='canned_files/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canned_responses', to='discount.whatsappchannel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canned_responses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
