# Generated by Django 5.2.8 on 2025-12-19 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0081_cannedresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappchannel',
            name='allow_agents_delete_msg',
            field=models.BooleanField(default=False, help_text='السماح للموظفين بحذف الرسائل'),
        ),
        migrations.AddField(
            model_name='whatsappchannel',
            name='business_about',
            field=models.CharField(blank=True, help_text='الحالة النصية في واتساب', max_length=130),
        ),
        migrations.AddField(
            model_name='whatsappchannel',
            name='business_address',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='whatsappchannel',
            name='business_description',
            field=models.TextField(blank=True, help_text='وصف النشاط التجاري'),
        ),
        migrations.AddField(
            model_name='whatsappchannel',
            name='business_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='whatsappchannel',
            name='business_website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='whatsappchannel',
            name='enable_collision_detection',
            field=models.BooleanField(default=True, help_text='تفعيل تنبيه التصادم بين الموظفين'),
        ),
        migrations.AddField(
            model_name='whatsappchannel',
            name='enable_welcome_msg',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='whatsappchannel',
            name='show_blue_ticks',
            field=models.BooleanField(default=True, help_text='إظهار علامة القراءة للعميل عند فتح المحادثة'),
        ),
        migrations.AddField(
            model_name='whatsappchannel',
            name='welcome_msg_body',
            field=models.TextField(blank=True, default='مرحباً بك! كيف يمكننا مساعدتك؟'),
        ),
    ]
