# Generated by Django 5.2.8 on 2025-12-19 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0082_whatsappchannel_allow_agents_delete_msg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappchannel',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Local profile image for dashboard', null=True, upload_to='channel_profiles/'),
        ),
    ]
