# Generated by Django 5.2.8 on 2025-12-21 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0083_whatsappchannel_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cannedresponse',
            name='created_at',
        ),
        migrations.AddField(
            model_name='cannedresponse',
            name='usage',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
