# Generated by Django 5.2.8 on 2025-12-21 23:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0084_remove_cannedresponse_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cannedresponse',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
