# Generated by Django 5.2.8 on 2025-12-22 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0085_cannedresponse_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='captions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
