# Generated by Django 5.2.8 on 2026-02-11 11:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0087_alter_contact_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='scriptflow',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scriptflow',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='scriptflow',
            name='plan_type',
            field=models.CharField(default='free', max_length=20),
        ),
        migrations.AddField(
            model_name='scriptflow',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
