# Generated by Django 5.2.8 on 2026-02-12 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0088_scriptflow_description_scriptflow_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignvisit',
            name='visit_meta',
            field=models.JSONField(blank=True, default=dict, help_text='Full payload from capture_visit (url, referrer, device, event, time_spent, etc.)'),
        ),
    ]
