# Generated by Django 5.2.8 on 2026-02-17 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0089_campaignvisit_visit_meta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('login_failed', 'Login Failed'), ('password_changed', 'Password Changed'), ('2fa_enabled', 'Two-Factor Auth Enabled'), ('2fa_disabled', 'Two-Factor Auth Disabled'), ('profile_updated', 'Profile Updated'), ('user_created', 'User Created'), ('user_updated', 'User Updated'), ('user_deleted', 'User Deleted'), ('invite_sent', 'Team Invite Sent'), ('invite_accepted', 'Team Invite Accepted'), ('member_removed', 'Team Member Removed'), ('order_created', 'Order Created'), ('order_updated', 'Order Updated'), ('order_status_changed', 'Order Status Changed'), ('order_agent_changed', 'Order Agent Changed'), ('order_bulk_assign', 'Orders Bulk Assigned'), ('order_imported', 'Orders Imported'), ('order_deleted', 'Order Deleted'), ('simple_order_created', 'Simple Order Created'), ('wa_message_sent', 'WhatsApp Message Sent'), ('wa_channel_created', 'WhatsApp Channel Created'), ('wa_channel_deleted', 'WhatsApp Channel Deleted'), ('wa_channel_updated', 'WhatsApp Channel Settings Updated'), ('wa_template_created', 'WhatsApp Template Created'), ('wa_template_updated', 'WhatsApp Template Updated'), ('wa_contact_assigned', 'Contact Assigned to Agent'), ('wa_contact_crm_updated', 'Contact CRM Updated'), ('flow_created', 'Flow Created'), ('flow_updated', 'Flow Updated'), ('flow_deleted', 'Flow Deleted'), ('autoreply_created', 'AutoReply Created'), ('autoreply_updated', 'AutoReply Updated'), ('autoreply_deleted', 'AutoReply Deleted'), ('campaign_flow_created', 'Campaign Flow Created'), ('campaign_flow_deleted', 'Campaign Flow Deleted'), ('product_updated', 'Product Updated'), ('product_filter', 'Product Filtered'), ('ws_connect', 'WebSocket Connected'), ('ws_disconnect', 'WebSocket Disconnected'), ('search_performed', 'Search Performed'), ('filter_applied', 'Filter Applied'), ('order_tracked', 'Order Tracked')], db_index=True, max_length=50),
        ),
    ]
