# Generated by Django 5.2.8 on 2026-05-04 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0090_expand_activity_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppCatalogProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.CharField(blank=True, max_length=64)),
                ('backup_price', models.CharField(blank=True, max_length=64)),
                ('coupon_code', models.CharField(blank=True, max_length=128)),
                ('currency', models.CharField(default='MAD', max_length=16)),
                ('description', models.TextField(blank=True)),
                ('delivery_options', models.TextField(blank=True)),
                ('category', models.CharField(default='general', max_length=64)),
                ('how_to_use', models.TextField(blank=True)),
                ('checkout_mode', models.CharField(default='standard_cod', max_length=64)),
                ('offer', models.JSONField(blank=True, default=list)),
                ('images', models.JSONField(blank=True, default=list)),
                ('videos', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_products', to='discount.whatsappchannel')),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
    ]
