# Generated by Django 5.2.8 on 2026-05-04 14:39

import discount.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _create_table_if_missing(schema_editor, Model):
    """
    Older DBs may already have these tables from migrations that were removed
    from the repo. SeparateDatabaseAndState runs DB ops before those models
    exist on the migration ProjectState, so we use the current model class here.
    """
    table = Model._meta.db_table
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        if table in connection.introspection.table_names(cursor):
            return
    schema_editor.create_model(Model)


def forwards_voice_gallery_entry(apps, schema_editor):
    from discount.models import VoiceGalleryEntry

    _create_table_if_missing(schema_editor, VoiceGalleryEntry)


def forwards_coach_conversation_message(apps, schema_editor):
    from discount.models import CoachConversationMessage

    _create_table_if_missing(schema_editor, CoachConversationMessage)


def forwards_voice_clone_request(apps, schema_editor):
    from discount.models import VoiceCloneRequest

    _create_table_if_missing(schema_editor, VoiceCloneRequest)


def forwards_channel_agent_routing(apps, schema_editor):
    from discount.models import ChannelAgentRouting

    _create_table_if_missing(schema_editor, ChannelAgentRouting)


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0091_whatsapp_catalog_product'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='VoiceGalleryEntry',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('provider', models.CharField(choices=[('ELEVENLABS', 'ElevenLabs'), ('OPENAI', 'OpenAI')], default='ELEVENLABS', max_length=20)),
                        ('elevenlabs_voice_id', models.CharField(help_text='ElevenLabs voice_id, or OpenAI voice name when provider is OpenAI.', max_length=64, unique=True)),
                        ('name', models.CharField(max_length=255)),
                        ('label', models.CharField(blank=True, max_length=255)),
                        ('preview_file', models.CharField(blank=True, max_length=255)),
                        ('preview_audio_file', models.FileField(blank=True, null=True, upload_to='voice_gallery_previews/')),
                        ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], default='FEMALE', max_length=10)),
                        ('tags', models.JSONField(blank=True, default=discount.models._default_json_list)),
                        ('native_arabic', models.BooleanField(default=False)),
                        ('language_code', models.CharField(blank=True, db_index=True, default='', max_length=32)),
                        ('dialect', models.CharField(choices=[('MA_DARIJA', 'Moroccan Darija'), ('SA_ARABIC', 'Saudi Arabic'), ('EG_ARABIC', 'Egyptian Arabic'), ('MSA', 'Modern Standard Arabic'), ('LEV_ARABIC', 'Levantine Arabic'), ('GULF_ARABIC', 'Gulf Arabic'), ('OTHER', 'Other / Multilingual')], db_index=True, default='MA_DARIJA', max_length=32)),
                        ('is_active', models.BooleanField(default=True)),
                        ('sort_order', models.PositiveIntegerField(default=0)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                    ],
                    options={
                        'ordering': ['sort_order', 'id'],
                    },
                ),
            ],
            database_operations=[
                migrations.RunPython(forwards_voice_gallery_entry, migrations.RunPython.noop),
            ],
        ),
        migrations.AddField(
            model_name='whatsappchannel',
            name='ai_auto_reply',
            field=models.BooleanField(default=False, help_text='Full autopilot: AI replies when no flow matches'),
        ),
        migrations.AddField(
            model_name='whatsappchannel',
            name='ai_llm_engine',
            field=models.CharField(blank=True, choices=[('AUTO', 'Auto (dialect-based routing)'), ('GPT_4O', 'GPT-4o (OpenAI)'), ('CLAUDE_3_5', 'Claude 3.5 Sonnet (Anthropic)')], default='AUTO', help_text='Default LLM for AI agent replies on this channel.', max_length=20),
        ),
        migrations.AddField(
            model_name='whatsappchannel',
            name='ai_order_capture',
            field=models.BooleanField(default=True, help_text='Automatically extract and save orders from conversations'),
        ),
        migrations.AddField(
            model_name='whatsappchannel',
            name='ai_override_rules',
            field=models.TextField(blank=True, default='', help_text='Custom sales rules from Admin coaching; appended to AI sales agent behavior for this channel.'),
        ),
        migrations.AddField(
            model_name='whatsappchannel',
            name='ai_routing_percentage',
            field=models.PositiveSmallIntegerField(default=0, help_text='AI share of new leads when Full Autopilot is ON (0-100). Human percentages + this must equal 100.'),
        ),
        migrations.AddField(
            model_name='whatsappchannel',
            name='ai_voice_enabled',
            field=models.BooleanField(default=False, help_text='Send AI replies as voice messages'),
        ),
        migrations.AddField(
            model_name='whatsappchannel',
            name='ai_voice_provider',
            field=models.CharField(choices=[('OPENAI', 'OpenAI TTS'), ('ELEVENLABS', 'ElevenLabs')], default='OPENAI', max_length=20),
        ),
        migrations.AddField(
            model_name='whatsappchannel',
            name='cloned_voice_id',
            field=models.CharField(blank=True, help_text='ElevenLabs cloned voice ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='whatsappchannel',
            name='dynamic_offline_redistribution',
            field=models.BooleanField(default=False, help_text='When ON, exclude offline agents and redistribute their percentages among online agents only.'),
        ),
        migrations.AddField(
            model_name='whatsappchannel',
            name='elevenlabs_api_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='whatsappchannel',
            name='elevenlabs_model_id',
            field=models.CharField(default='eleven_multilingual_v2', help_text='ElevenLabs model; use eleven_multilingual_v2 for natural Arabic.', max_length=64),
        ),
        migrations.AddField(
            model_name='whatsappchannel',
            name='order_notify_email',
            field=models.EmailField(blank=True, help_text='Email address for order notifications (when method is Email).', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='whatsappchannel',
            name='order_notify_method',
            field=models.CharField(blank=True, choices=[('', 'Off'), ('EMAIL', 'Email'), ('WHATSAPP', 'WhatsApp')], default='', help_text='Send owner a notification when AI creates an order.', max_length=20),
        ),
        migrations.AddField(
            model_name='whatsappchannel',
            name='order_notify_whatsapp_phone',
            field=models.CharField(blank=True, help_text='Phone (with country code) for WhatsApp order notifications.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='whatsappchannel',
            name='selected_voice_id',
            field=models.CharField(blank=True, help_text='ElevenLabs voice ID from the gallery (e.g. Layla, Rachel).', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='whatsappchannel',
            name='voice_cloning_enabled',
            field=models.BooleanField(default=False, help_text='Clone your voice (Premium only)'),
        ),
        migrations.AddField(
            model_name='whatsappchannel',
            name='voice_delay_seconds',
            field=models.PositiveSmallIntegerField(default=20, help_text='Delay before sending voice (10-30 sec)'),
        ),
        migrations.AddField(
            model_name='whatsappchannel',
            name='voice_dialect',
            field=models.CharField(choices=[('MA_DARIJA', 'Moroccan Darija'), ('SA_ARABIC', 'Saudi Arabic'), ('EG_ARABIC', 'Egyptian Arabic'), ('MSA', 'Modern Standard Arabic'), ('LEV_ARABIC', 'Levantine Arabic'), ('GULF_ARABIC', 'Gulf Arabic'), ('OTHER', 'Other / Multilingual')], default='MA_DARIJA', help_text='Dialect aligned with the current voice (gallery selection or approved clone).', max_length=32),
        ),
        migrations.AddField(
            model_name='whatsappchannel',
            name='voice_gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], default='FEMALE', max_length=10),
        ),
        migrations.AddField(
            model_name='whatsappchannel',
            name='voice_language',
            field=models.CharField(choices=[('AUTO', 'Auto-Detect'), ('AR_MA', 'Arabic (Morocco)'), ('AR_SA', 'Arabic (Saudi)'), ('FR_FR', 'French (France)'), ('EN_US', 'English (US)')], default='AUTO', max_length=10),
        ),
        migrations.AddField(
            model_name='whatsappchannel',
            name='voice_preview_url',
            field=models.URLField(blank=True, help_text='Sample audio URL for the selected voice in the UI.', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='whatsappchannel',
            name='voice_provider',
            field=models.CharField(choices=[('OPENAI', 'OpenAI TTS'), ('ELEVENLABS', 'ElevenLabs')], default='OPENAI', max_length=20),
        ),
        migrations.AddField(
            model_name='whatsappchannel',
            name='voice_similarity',
            field=models.FloatField(default=0.75, help_text='0.0-1.0 Similarity/Clarity'),
        ),
        migrations.AddField(
            model_name='whatsappchannel',
            name='voice_stability',
            field=models.FloatField(default=0.5, help_text='0.0-1.0 Emotion/Stability'),
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='CoachConversationMessage',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('role', models.CharField(choices=[('user', 'user'), ('assistant', 'assistant')], max_length=20)),
                        ('content', models.TextField()),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_conversation_messages', to='discount.whatsappchannel')),
                        ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_conversation_messages', to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'ordering': ['created_at'],
                    },
                ),
            ],
            database_operations=[
                migrations.RunPython(forwards_coach_conversation_message, migrations.RunPython.noop),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='VoiceCloneRequest',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('audio_file', models.FileField(upload_to='voice_clone_requests/%Y/%m/')),
                        ('consent_agreed', models.BooleanField(default=False)),
                        ('dialect', models.CharField(choices=[('MA_DARIJA', 'Moroccan Darija'), ('SA_ARABIC', 'Saudi Arabic'), ('EG_ARABIC', 'Egyptian Arabic'), ('MSA', 'Modern Standard Arabic'), ('LEV_ARABIC', 'Levantine Arabic'), ('GULF_ARABIC', 'Gulf Arabic'), ('OTHER', 'Other / Multilingual')], default='MA_DARIJA', max_length=32)),
                        ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                        ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                        ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_clone_requests', to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'ordering': ['-created_at'],
                    },
                ),
            ],
            database_operations=[
                migrations.RunPython(forwards_voice_clone_request, migrations.RunPython.noop),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='ChannelAgentRouting',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('routing_percentage', models.PositiveSmallIntegerField(default=0)),
                        ('is_accepting_chats', models.BooleanField(default=True)),
                        ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_routing_configs', to=settings.AUTH_USER_MODEL)),
                        ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_routing_configs', to='discount.whatsappchannel')),
                    ],
                    options={
                        'db_table': 'discount_channelagentrouting',
                        'unique_together': {('channel', 'agent')},
                    },
                ),
            ],
            database_operations=[
                migrations.RunPython(forwards_channel_agent_routing, migrations.RunPython.noop),
            ],
        ),
    ]
