# Generated by Django 5.2.8 on 2026-02-20 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0100_simpleorder_created_by_ai_aiusagelog'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='aiusagelog',
            new_name='discount_ai_channel_91b405_idx',
            old_name='discount_ai_channel_6b8c2a_idx',
        ),
        migrations.RenameIndex(
            model_name='chatsession',
            new_name='discount_ch_channel_54c635_idx',
            old_name='discount_ch_channel_7a8b0d_idx',
        ),
        migrations.AlterField(
            model_name='nodemedia',
            name='description',
            field=models.CharField(blank=True, help_text='Label for GPT, e.g. Product Close-up, How-to-use Video', max_length=255),
        ),
        migrations.AlterField(
            model_name='plan',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
