# Generated by Django 5.2.8 on 2026-02-21 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0104_follow_up_node_and_task'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='followupsentlog',
            new_name='discount_fo_channel_2b6935_idx',
            old_name='discount_fol_channel_2d3e4a_idx',
        ),
        migrations.RenameIndex(
            model_name='followuptask',
            new_name='discount_fo_channel_5e5cc0_idx',
            old_name='discount_fol_channel_7a8b0d_idx',
        ),
        migrations.RenameIndex(
            model_name='followuptask',
            new_name='discount_fo_status_4639ef_idx',
            old_name='discount_fol_status_8c9e1f_idx',
        ),
        migrations.AlterField(
            model_name='node',
            name='node_voice_id',
            field=models.CharField(blank=True, help_text='Voice ID for this node (e.g. ElevenLabs) – legacy; prefer persona', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='voicepersona',
            name='voice_id',
            field=models.CharField(help_text='ElevenLabs or OpenAI voice ID', max_length=120),
        ),
    ]
