# Generated by Django 5.2.8 on 2026-02-21 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0105_chatsession_hitl_handoverlog'),
        ('discount', '0105_rename_discount_fol_channel_2d3e4a_idx_discount_fo_channel_2b6935_idx_and_more'),
    ]

    operations = [
    ]
