# Generated by Django 5.2.8 on 2026-02-21 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0106_merge_20260221_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleSheetsConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spreadsheet_id', models.CharField(help_text='Spreadsheet ID from the Google Sheets URL', max_length=128)),
                ('sheet_name', models.CharField(default='Orders', max_length=128)),
                ('service_account_json_encrypted', models.TextField(blank=True, null=True)),
                ('column_mapping', models.JSONField(blank=True, default=dict, help_text='{"A": "customer_name", "B": "phone", "C": "city", ...}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Google Sheets config',
                'verbose_name_plural': 'Google Sheets configs',
            },
        ),
        migrations.CreateModel(
            name='GoogleSheetsNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Google Sheets node config',
                'verbose_name_plural': 'Google Sheets node configs',
            },
        ),
        migrations.RenameIndex(
            model_name='handoverlog',
            new_name='discount_ha_channel_d8bf24_idx',
            old_name='discount_han_channel_9a1b2c_idx',
        ),
        migrations.AddField(
            model_name='simpleorder',
            name='sheets_export_status',
            field=models.CharField(blank=True, choices=[('', '—'), ('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], help_text='Google Sheets export status for dashboard re-sync', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='googlesheetsconfig',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_sheets_config', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='googlesheetsnode',
            name='config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nodes', to='discount.googlesheetsconfig'),
        ),
        migrations.AddField(
            model_name='googlesheetsnode',
            name='node',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_sheets_config', to='discount.node'),
        ),
    ]
