# Generated by Django 5.2.8 on 2026-02-23 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0109_googlesheetsconfig_sheets_mapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='simpleorder',
            name='expected_delivery_date',
            field=models.DateField(blank=True, help_text='Expected delivery date.', null=True, verbose_name='تاريخ التوصيل المتوقع'),
        ),
        migrations.AddField(
            model_name='simpleorder',
            name='shipping_company',
            field=models.CharField(blank=True, help_text='Name of the shipping/delivery company.', max_length=200, null=True, verbose_name='شركة الشحن'),
        ),
    ]
