# Generated by Django 5.2.8

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0112_add_product_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='currency',
            field=models.CharField(blank=True, default='MAD', max_length=10, verbose_name='العملة'),
        ),
    ]
