# Generated by Django 5.2.8 on 2026-03-17 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0121_coach_conversation_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='required_order_fields',
            field=models.JSONField(blank=True, default=list, help_text='List of order fields the AI must collect for this product (e.g. ["customer_name", "phone_number"] or ["customer_name", "phone_number", "shipping_city", "shipping_address"]).', null=True),
        ),
    ]
