# Generated by Django 5.2.8 on 2026-03-23 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0125_add_plan_channel_team_limits'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='chatsession',
            new_name='discount_ch_channel_2e5348_idx',
            old_name='discount_ch_channel_4f8e2b_idx',
        ),
        migrations.AddField(
            model_name='customuser',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='stripe_subscription_status',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
