# Generated by Django 5.2.8 on 2026-03-23 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0126_rename_discount_ch_channel_4f8e2b_idx_discount_ch_channel_2e5348_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='low_balance_alert_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='total_tokens_used',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='wallet_balance',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
    ]
