# Generated by Django 5.2.8 on 2026-03-26 01:27

import discount.models
from django.db import migrations, models


def seed_voice_gallery(apps, schema_editor):
    VoiceGalleryEntry = apps.get_model("discount", "VoiceGalleryEntry")
    rows = [
        {
            "elevenlabs_voice_id": "21m00Tcm4TlvDq8ikWAM",
            "name": "Rachel – Professional Sales",
            "label": "Rachel – Professional Sales",
            "preview_file": "rachel.mp3",
            "gender": "FEMALE",
            "tags": ["Multilingual", "High Quality", "Natural"],
            "native_arabic": True,
            "sort_order": 10,
        },
        {
            "elevenlabs_voice_id": "pNInz6obpgDQGcFmaJgB",
            "name": "Adam – Clear & Trustworthy",
            "label": "Adam – Clear & Trustworthy",
            "preview_file": "adam.mp3",
            "gender": "MALE",
            "tags": ["Multilingual", "High Quality"],
            "native_arabic": True,
            "sort_order": 20,
        },
        {
            "elevenlabs_voice_id": "EXAVITQu4vr4xnSDxMaL",
            "name": "Bella – Soft Consultative",
            "label": "Bella – Soft Consultative",
            "preview_file": "bella.mp3",
            "gender": "FEMALE",
            "tags": ["Multilingual", "Natural"],
            "native_arabic": True,
            "sort_order": 30,
        },
        {
            "elevenlabs_voice_id": "ErXwobaYiN019PkySvjV",
            "name": "Antoni – Friendly Closer",
            "label": "Antoni – Friendly Closer",
            "preview_file": "antoni.mp3",
            "gender": "MALE",
            "tags": ["Multilingual", "High Quality"],
            "native_arabic": False,
            "sort_order": 40,
        },
        {
            "elevenlabs_voice_id": "MF3mGyEYCl7XYWbV9V6O",
            "name": "Elli – Arabic-forward",
            "label": "Elli – Arabic-forward",
            "preview_file": "elli.mp3",
            "gender": "FEMALE",
            "tags": ["Multilingual", "High Quality", "Natural"],
            "native_arabic": True,
            "sort_order": 50,
        },
        {
            "elevenlabs_voice_id": "TxGEqnHWrfWFTfGW9XjX",
            "name": "Josh – Confident Pitch",
            "label": "Josh – Confident Pitch",
            "preview_file": "josh.mp3",
            "gender": "MALE",
            "tags": ["Multilingual", "Natural"],
            "native_arabic": False,
            "sort_order": 60,
        },
        {
            "elevenlabs_voice_id": "VR6AewLTigWG4xSOukaG",
            "name": "Arnold – Authoritative",
            "label": "Arnold – Authoritative",
            "preview_file": "arnold.mp3",
            "gender": "MALE",
            "tags": ["Multilingual", "High Quality"],
            "native_arabic": False,
            "sort_order": 70,
        },
        {
            "elevenlabs_voice_id": "onwK4e9ZLuTAKqWW03F9",
            "name": "Daniel – Refined Tone",
            "label": "Daniel – Refined Tone",
            "preview_file": "daniel.mp3",
            "gender": "MALE",
            "tags": ["Multilingual", "Natural"],
            "native_arabic": False,
            "sort_order": 80,
        },
        {
            "elevenlabs_voice_id": "D38z5RcWu1voky8WS1ja",
            "name": "Lily – French & Arabic",
            "label": "Lily – French & Arabic",
            "preview_file": "lily.mp3",
            "gender": "FEMALE",
            "tags": ["Multilingual", "French", "Natural"],
            "native_arabic": False,
            "sort_order": 90,
        },
        {
            "elevenlabs_voice_id": "flq6f7yk4E4fJM5XTYuZ",
            "name": "Michael – Neutral Pro",
            "label": "Michael – Neutral Pro",
            "preview_file": "michael.mp3",
            "gender": "MALE",
            "tags": ["Multilingual", "High Quality"],
            "native_arabic": False,
            "sort_order": 100,
        },
    ]
    for row in rows:
        vid = row["elevenlabs_voice_id"]
        defaults = {k: v for k, v in row.items() if k != "elevenlabs_voice_id"}
        defaults.setdefault("is_active", True)
        VoiceGalleryEntry.objects.update_or_create(elevenlabs_voice_id=vid, defaults=defaults)


def unseed_voice_gallery(apps, schema_editor):
    VoiceGalleryEntry = apps.get_model("discount", "VoiceGalleryEntry")
    VoiceGalleryEntry.objects.filter(
        elevenlabs_voice_id__in=[
            "21m00Tcm4TlvDq8ikWAM",
            "pNInz6obpgDQGcFmaJgB",
            "EXAVITQu4vr4xnSDxMaL",
            "ErXwobaYiN019PkySvjV",
            "MF3mGyEYCl7XYWbV9V6O",
            "TxGEqnHWrfWFTfGW9XjX",
            "VR6AewLTigWG4xSOukaG",
            "onwK4e9ZLuTAKqWW03F9",
            "D38z5RcWu1voky8WS1ja",
            "flq6f7yk4E4fJM5XTYuZ",
        ]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0129_customuser_is_suspended_customuser_suspension_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceGalleryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elevenlabs_voice_id', models.CharField(help_text='ElevenLabs voice_id (from their API / voice library).', max_length=64, unique=True)),
                ('name', models.CharField(help_text='Short display name.', max_length=255)),
                ('label', models.CharField(blank=True, help_text='Optional longer label; defaults to name if empty.', max_length=255)),
                ('preview_file', models.CharField(blank=True, help_text='Filename only, e.g. rachel.mp3 — file must live under static/audio/voice-previews/', max_length=255)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], default='FEMALE', max_length=10)),
                ('tags', models.JSONField(blank=True, default=discount.models._default_json_list, help_text='List of strings, e.g. ["Multilingual", "High Quality"]. Include "French" for French filter.')),
                ('native_arabic', models.BooleanField(default=False, help_text='If True, voice appears in “Optimized for Arabic” gallery filter.')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first in the gallery.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Voice Gallery entry',
                'verbose_name_plural': 'Voice Gallery entries',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.RunPython(seed_voice_gallery, unseed_voice_gallery),
    ]
