# Generated by Django 5.2.8 on 2026-03-26 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0130_voice_gallery_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='voicegalleryentry',
            name='preview_audio_file',
            field=models.FileField(blank=True, help_text='Optional MP3 upload for the preview. If set, the gallery uses this file instead of `preview_file`.', null=True, upload_to='voice_gallery_previews/'),
        ),
    ]
