# Generated by Django 5.2.8 on 2026-03-30 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0138_voice_gallery_provider_bot_language'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='extrachannelslotsubscription',
            new_name='discount_ex_billing_c34026_idx',
            old_name='dc_ecss_owner_active',
        ),
    ]
