# Generated by Django 5.2.8 on 2026-05-03 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0143_whatsappchannel_ai_llm_engine'),
    ]

    operations = [
        migrations.AddField(
            model_name='simpleorder',
            name='order_notes',
            field=models.TextField(blank=True, help_text='Delivery timing, alternate phone, and other instructions (appended by AI or staff).', null=True, verbose_name='ملاحظات الطلب'),
        ),
    ]
