# Generated by Django 5.2.8 on 2026-05-07 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0092_voice_settings_and_routing'),
        ('discount', '0144_simpleorder_order_notes'),
    ]

    operations = [
    ]
