# Generated by Django 5.2.8 on 2026-05-07 11:25

import discount.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0145_merge_20260507_1101'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channelagentrouting',
            options={'verbose_name': 'Channel Agent Routing', 'verbose_name_plural': 'Channel Agent Routings'},
        ),
        migrations.AlterModelOptions(
            name='voiceclonerequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Voice clone request', 'verbose_name_plural': 'Voice clone requests'},
        ),
        migrations.AlterModelOptions(
            name='voicegalleryentry',
            options={'ordering': ['sort_order', 'id'], 'verbose_name': 'Voice Gallery entry', 'verbose_name_plural': 'Voice Gallery entries'},
        ),
        migrations.AlterField(
            model_name='channelagentrouting',
            name='is_accepting_chats',
            field=models.BooleanField(default=True, help_text='If False, agent is excluded from new assignments; existing sticky assignments remain.'),
        ),
        migrations.AlterField(
            model_name='channelagentrouting',
            name='routing_percentage',
            field=models.PositiveSmallIntegerField(default=0, help_text='Weight for new lead distribution (0-100). Sum for channel must be 100.'),
        ),
        migrations.AlterField(
            model_name='voiceclonerequest',
            name='dialect',
            field=models.CharField(choices=[('MA_DARIJA', 'Moroccan Darija'), ('SA_ARABIC', 'Saudi Arabic'), ('EG_ARABIC', 'Egyptian Arabic'), ('MSA', 'Modern Standard Arabic'), ('LEV_ARABIC', 'Levantine Arabic'), ('GULF_ARABIC', 'Gulf Arabic'), ('OTHER', 'Other / Multilingual')], default='MA_DARIJA', help_text='Dialect the merchant declares for this sample (stored with the request and applied on approval).', max_length=32),
        ),
        migrations.AlterField(
            model_name='voicegalleryentry',
            name='dialect',
            field=models.CharField(choices=[('MA_DARIJA', 'Moroccan Darija'), ('SA_ARABIC', 'Saudi Arabic'), ('EG_ARABIC', 'Egyptian Arabic'), ('MSA', 'Modern Standard Arabic'), ('LEV_ARABIC', 'Levantine Arabic'), ('GULF_ARABIC', 'Gulf Arabic'), ('OTHER', 'Other / Multilingual')], db_index=True, default='MA_DARIJA', help_text='Primary spoken dialect for this voice; drives LLM output to match TTS pronunciation.', max_length=32),
        ),
        migrations.AlterField(
            model_name='voicegalleryentry',
            name='elevenlabs_voice_id',
            field=models.CharField(help_text='ElevenLabs voice_id, or OpenAI voice name (alloy, echo, fable, onyx, nova, shimmer) when provider is OpenAI.', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='voicegalleryentry',
            name='label',
            field=models.CharField(blank=True, help_text='Optional longer label; defaults to name if empty.', max_length=255),
        ),
        migrations.AlterField(
            model_name='voicegalleryentry',
            name='language_code',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Primary locale for filtering, e.g. AR_MA, FR_FR, EN_US (use underscore). Leave empty for multilingual / any language.', max_length=32),
        ),
        migrations.AlterField(
            model_name='voicegalleryentry',
            name='name',
            field=models.CharField(help_text='Short display name.', max_length=255),
        ),
        migrations.AlterField(
            model_name='voicegalleryentry',
            name='native_arabic',
            field=models.BooleanField(default=False, help_text='If True, voice appears in “Optimized for Arabic” gallery filter.'),
        ),
        migrations.AlterField(
            model_name='voicegalleryentry',
            name='preview_audio_file',
            field=models.FileField(blank=True, help_text='Optional MP3 upload for the preview. If set, the gallery uses this file instead of `preview_file`.', null=True, upload_to='voice_gallery_previews/'),
        ),
        migrations.AlterField(
            model_name='voicegalleryentry',
            name='preview_file',
            field=models.CharField(blank=True, help_text='Filename only, e.g. rachel.mp3 — file must live under static/audio/voice-previews/', max_length=255),
        ),
        migrations.AlterField(
            model_name='voicegalleryentry',
            name='provider',
            field=models.CharField(choices=[('ELEVENLABS', 'ElevenLabs'), ('OPENAI', 'OpenAI')], default='ELEVENLABS', help_text='TTS backend: ElevenLabs API or OpenAI audio.speech (tts-1).', max_length=20),
        ),
        migrations.AlterField(
            model_name='voicegalleryentry',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, help_text='Lower numbers appear first in the gallery.'),
        ),
        migrations.AlterField(
            model_name='voicegalleryentry',
            name='tags',
            field=models.JSONField(blank=True, default=discount.models._default_json_list, help_text='List of strings, e.g. ["Multilingual", "High Quality"]. Include "French" for French filter.'),
        ),
        migrations.AlterField(
            model_name='whatsappchannel',
            name='ai_llm_engine',
            field=models.CharField(blank=True, choices=[('AUTO', 'Auto (dialect-based routing)'), ('GPT_4O', 'GPT-4o (OpenAI)'), ('CLAUDE_3_5', 'Claude 3.5 Sonnet (Anthropic)')], default='AUTO', help_text='Default LLM for AI agent replies on this channel. Flow node AI Engine overrides when set to GPT or Claude.', max_length=20),
        ),
        migrations.AlterField(
            model_name='whatsappchannel',
            name='ai_override_rules',
            field=models.TextField(blank=True, default='', help_text='Custom sales rules from Admin coaching; overrides default AI behavior for this channel.'),
        ),
        migrations.DeleteModel(
            name='WhatsAppCatalogProduct',
        ),
    ]
