# Generated by Django 5.2.8 on 2026-05-26 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0146_alter_channelagentrouting_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='is_completed',
            field=models.BooleanField(db_index=True, default=False, help_text='True when the customer successfully completed the Node goal (e.g. order submitted via submit_customer_order). Session becomes inactive; next message starts fresh trigger evaluation.'),
        ),
    ]
