# Generated by Django 5.2.8 on 2026-05-27 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0147_chatsession_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='digital_file',
            field=models.FileField(blank=True, help_text='Upload the deliverable directly (PDF, ZIP, …). Used when the file is small enough to host on this server.', null=True, upload_to='digital_assets/', verbose_name='Digital file'),
        ),
        migrations.AddField(
            model_name='products',
            name='digital_url',
            field=models.URLField(blank=True, help_text='External link (Google Drive, Mega, S3…) for large files. Sent to the customer after order confirmation.', null=True, verbose_name='Digital download URL'),
        ),
        migrations.AddField(
            model_name='products',
            name='is_digital',
            field=models.BooleanField(db_index=True, default=False, help_text='Mark True for e-books, courses, licence keys, etc. When True the AI Agent collects Name + Email instead of a shipping address, and the checkout_mode is automatically treated as "digital".', verbose_name='Digital product'),
        ),
        migrations.AlterField(
            model_name='products',
            name='checkout_mode',
            field=models.CharField(blank=True, choices=[('quick_lead', 'Quick Lead (Name & Phone only)'), ('standard_cod', 'Standard COD (Name, Phone, City)'), ('strict_cod', 'Strict COD (Full Address)'), ('digital', 'Digital Delivery (Name & Email — no shipping address)')], default='standard_cod', help_text='Controls what the AI Sales Agent collects before placing an order. quick_lead = Name+Phone; standard_cod = Name+Phone+City; strict_cod = Name+Phone+City+Address; digital = Name+Email (no shipping).', max_length=20, verbose_name='Checkout mode (AI data collection)'),
        ),
    ]
