# Generated by Django 5.2.8 on 2026-05-27 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0148_digital_product_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='fulfillment_message',
            field=models.TextField(blank=True, help_text='Custom thank-you message sent automatically to the customer after digital product purchase. Leave blank for a system default message.', null=True, verbose_name='Fulfillment message'),
        ),
    ]
