# Generated by Django 5.2.8 on 2026-05-28 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0149_product_fulfillment_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='collect_customer_info',
            field=models.BooleanField(default=True, help_text='Digital products only. When True the AI Agent asks for Name + Email before delivering the product. When False the AI triggers the order immediately using the WhatsApp phone number — no questions asked.', verbose_name='Collect customer info'),
        ),
    ]
