# Generated by Django 5.2.8 on 2026-05-28 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0150_product_collect_customer_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='checkout_mode',
            field=models.CharField(blank=True, choices=[('quick_lead', 'Quick Lead (Name & Phone only)'), ('standard_cod', 'Standard COD (Name, Phone, City)'), ('strict_cod', 'Strict COD (Full Address)'), ('digital', 'Digital Delivery (Name & Email — no shipping address)'), ('direct_sale', 'Direct Sale (No information required — instant submit)')], default='standard_cod', help_text='Controls what the AI Sales Agent collects before placing an order. quick_lead = Name+Phone; standard_cod = Name+Phone+City; strict_cod = Name+Phone+City+Address; digital = Name+Email (no shipping); direct_sale = No info required — AI submits instantly on purchase intent.', max_length=20, verbose_name='Checkout mode (AI data collection)'),
        ),
        migrations.CreateModel(
            name='StorePaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(choices=[('cih_bank', 'CIH Bank'), ('attijariwafa', 'Attijariwafa Bank'), ('cpm', 'CPM (Maroc)'), ('barid_cash', 'Barid Cash'), ('cash_plus', 'Cash Plus'), ('orange_money', 'Orange Money'), ('paypal', 'PayPal'), ('stripe', 'Stripe'), ('wise', 'Wise (TransferWise)'), ('other', 'Other')], max_length=50)),
                ('display_name', models.CharField(blank=True, help_text='Custom label shown to customers. Leave blank to use the provider name.', max_length=100)),
                ('account_details_encrypted', models.TextField(help_text='Account number / email / IBAN — stored Fernet-encrypted at rest.')),
                ('instructions', models.TextField(blank=True, help_text='e.g., "Include order number in transfer note."')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Store Payment Method',
                'verbose_name_plural': 'Store Payment Methods',
                'ordering': ['provider_name', 'id'],
            },
        ),
    ]
