# Generated by Django 5.2.8 on 2026-05-28 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0151_store_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='storepaymentmethod',
            name='account_holder_name',
            field=models.CharField(blank=True, help_text='Full name of the account holder (bank transfers only).', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='storepaymentmethod',
            name='account_details_encrypted',
            field=models.TextField(help_text='RIB (24 digits) or email — stored Fernet-encrypted at rest.'),
        ),
        migrations.AlterField(
            model_name='storepaymentmethod',
            name='provider_name',
            field=models.CharField(choices=[('cih_bank', 'CIH Bank'), ('attijariwafa', 'Attijariwafa Bank'), ('boa', 'Bank of Africa'), ('paypal', 'PayPal'), ('wise', 'Wise')], max_length=50),
        ),
    ]
