# Generated by Django 5.2.8 on 2026-05-28 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0152_payment_method_refine'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_payment_receipt',
            field=models.BooleanField(db_index=True, default=False, help_text='True when the message was identified as a payment receipt from the customer.'),
        ),
        migrations.AddField(
            model_name='message',
            name='receipt_status',
            field=models.CharField(blank=True, choices=[('pending_review', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], help_text='Merchant review status for this payment receipt.', max_length=20, null=True),
        ),
    ]
