# Generated by Django 5.2.8 on 2026-05-29 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0153_digital_fulfillment_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='simpleorder',
            name='customer_email',
            field=models.EmailField(blank=True, help_text='Set for digital products that collect customer info.', max_length=254, null=True, verbose_name='بريد العميل'),
        ),
        migrations.AddField(
            model_name='simpleorder',
            name='is_digital',
            field=models.BooleanField(db_index=True, default=False, help_text='Copied from the product at order creation time.'),
        ),
        migrations.AlterField(
            model_name='simpleorder',
            name='customer_name',
            field=models.CharField(blank=True, help_text='Blank for Direct-Sale digital orders.', max_length=200, null=True, verbose_name='اسم العميل'),
        ),
    ]
