# Generated by Django 5.2.8 on 2026-05-30 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0158_simpleorder_payment_rejection_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitalassetstock',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
