# Generated by Django 5.2.8 on 2026-06-02 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0163_products_digital_type_iptv_consent'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='merchantriskevent',
            new_name='discount_me_merchan_764320_idx',
            old_name='discount_me_merchan_8a1f2c_idx',
        ),
        migrations.RenameIndex(
            model_name='merchantriskevent',
            new_name='discount_me_merchan_0f71a5_idx',
            old_name='discount_me_merchan_4b3e9d_idx',
        ),
    ]
