# Generated by Django 5.2.8 on 2026-08-25 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0164_rename_discount_me_merchan_8a1f2c_idx_discount_me_merchan_764320_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='content_media_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
