# Generated by Django 5.2.8 on 2026-08-25 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0165_node_content_media_url_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppFlowSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('lead_generation', 'Generate leads'), ('feedback', 'Receive feedback'), ('collect_order', 'Collect order')], default='lead_generation', max_length=32)),
                ('customer_phone', models.CharField(db_index=True, max_length=30)),
                ('customer_name', models.CharField(blank=True, default='', max_length=200)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('flow_token', models.CharField(blank=True, db_index=True, default='', max_length=200)),
                ('meta_flow_id', models.CharField(blank=True, default='', max_length=64)),
                ('whatsapp_message_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('automation_flow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_flow_submissions', to='discount.flow')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_flow_submissions', to='discount.whatsappchannel')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_flow_submissions', to='discount.contact')),
                ('node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_flow_submissions', to='discount.node')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_flow_submissions', to='discount.simpleorder')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_flow_submissions', to='discount.products')),
            ],
            options={
                'verbose_name': 'WhatsApp Flow submission',
                'verbose_name_plural': 'WhatsApp Flow submissions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['channel', 'created_at'], name='discount_wh_channel_2a240c_idx'), models.Index(fields=['channel', 'customer_phone'], name='discount_wh_channel_14b288_idx')],
            },
        ),
    ]
