# Generated by Django 5.2.8 on 2026-08-26 19:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0166_whatsappflowsubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCheckoutFormCopy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_text', models.CharField(blank=True, default='', max_length=60)),
                ('body_text', models.CharField(blank=True, default='', max_length=1024)),
                ('footer_text', models.CharField(blank=True, default='', max_length=60)),
                ('cta_label', models.CharField(blank=True, default='', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_checkout_form_copies', to='discount.products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkout_form_copies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User checkout form copy',
                'verbose_name_plural': 'User checkout form copies',
                'unique_together': {('user', 'product')},
            },
        ),
    ]
