# Generated by Django 5.2.8 on 2026-08-31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0167_user_checkout_form_copy'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=30)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blocked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocked_customers', to=settings.AUTH_USER_MODEL)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_customers', to='discount.whatsappchannel')),
            ],
            options={
                'verbose_name': 'Blocked customer',
                'verbose_name_plural': 'Blocked customers',
                'indexes': [models.Index(fields=['channel', 'phone'], name='blocked_cust_ch_phone_idx')],
                'unique_together': {('channel', 'phone')},
            },
        ),
    ]
