# Generated by Django 5.2.8 on 2026-09-01 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0169_coach_conversation'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='coachconversation',
            new_name='discount_co_channel_ef6373_idx',
            old_name='discount_co_channel_7f3a2b_idx',
        ),
        migrations.AlterField(
            model_name='products',
            name='stock_format',
            field=models.CharField(choices=[('single', 'Single keys/codes (one per line)'), ('combo', 'Email & Password (separated by ":")'), ('iptv', 'IPTV / Xtream / M3U (one per line)')], default='single', help_text='Controls how each row of bulk-pasted digital stock is parsed and delivered. "single" stores one opaque value per row; "combo" expects "email:password" on every line; "iptv" stores Xtream credentials or M3U links (opaque per line).', max_length=16, verbose_name='Digital stock format'),
        ),
    ]
