# Generated by Django 5.2.8 on 2026-09-08 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0180_checkout_force_voice_mode'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='knowledgegapescalation',
            new_name='discount_kn_channel_e84491_idx',
            old_name='discount_kge_ch_st_dt_idx',
        ),
        migrations.RenameIndex(
            model_name='knowledgegapescalation',
            new_name='discount_kn_channel_832358_idx',
            old_name='discount_kge_ch_ph_st_idx',
        ),
        migrations.RenameIndex(
            model_name='productknowledgebase',
            new_name='discount_pr_product_4c39fd_idx',
            old_name='discount_pkb_prod_upd_idx',
        ),
        migrations.RenameIndex(
            model_name='whatsappadclick',
            new_name='discount_wh_channel_20a299_idx',
            old_name='discount_ad_ch_src_dt_idx',
        ),
        migrations.RenameIndex(
            model_name='whatsappadclick',
            new_name='discount_wh_channel_ce3ef9_idx',
            old_name='discount_ad_ch_ph_dt_idx',
        ),
        migrations.RenameIndex(
            model_name='whatsappcheckoutstate',
            new_name='discount_wh_channel_546b3f_idx',
            old_name='discount_wh_channel_0e8c1a_idx',
        ),
        migrations.RenameIndex(
            model_name='whatsappcheckoutstate',
            new_name='discount_wh_channel_0ef137_idx',
            old_name='discount_wh_channel_9f2b4d_idx',
        ),
        migrations.RenameIndex(
            model_name='whatsappcheckoutstate',
            new_name='discount_wh_channel_2b301d_idx',
            old_name='discount_wh_ch_adsrc_idx',
        ),
        migrations.AlterField(
            model_name='message',
            name='media_type',
            field=models.CharField(blank=True, choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('document', 'Document'), ('sticker', 'Sticker')], max_length=20, null=True),
        ),
    ]
