# Generated by Django (initial)

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("discount", "0017_campaignvisit_externalorder"),  # CampaignVisit exists
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Store",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("owner", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="owned_stores", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Attribution",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("utm_campaign", models.CharField(blank=True, max_length=200)),
                ("utm_source", models.CharField(blank=True, max_length=200)),
                ("ad_id", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("campaign_visit", models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="order_attribution", to="discount.campaignvisit")),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("phone", models.CharField(db_index=True, max_length=32)),
                ("address", models.TextField(blank=True)),
                ("city", models.CharField(blank=True, max_length=120)),
                ("product_name", models.CharField(max_length=255)),
                ("price", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("status", models.CharField(choices=[("NEW", "New"), ("PENDING_CONFIRMATION", "Pending confirmation"), ("CONFIRMED", "Confirmed"), ("SHIPPED", "Shipped"), ("DELIVERED", "Delivered"), ("CANCELED", "Canceled"), ("RETURNED", "Returned"), ("NO_ANSWER", "No answer")], default="NEW", max_length=32)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("assigned_agent", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="assigned_orders", to=settings.AUTH_USER_MODEL)),
                ("attribution_data", models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="order", to="orders.attribution")),
                ("store", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="orders", to="orders.store")),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["phone"], name="orders_order_phone_idx"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["status"], name="orders_order_status_idx"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["created_at"], name="orders_order_created_idx"),
        ),
    ]
