# Generated by Django 5.2.8 on 2026-02-12 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='order',
            new_name='orders_orde_phone_7bc88b_idx',
            old_name='orders_order_phone_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='orders_orde_status_c6dd84_idx',
            old_name='orders_order_status_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='orders_orde_created_0e92de_idx',
            old_name='orders_order_created_idx',
        ),
    ]
