# Generated by Django 5.2.8

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='client_data',
            field=models.JSONField(blank=True, default=dict, help_text='Full visit/capture payload (url, referrer, device, event, time_spent, utm_*, etc.)'),
        ),
    ]
