# Generated by Django 5.2.8 on 2026-02-20 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_client_data'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='order',
            name='orders_orde_phone_7bc88b_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='orders_orde_status_c6dd84_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='orders_orde_created_0e92de_idx',
        ),
        migrations.AlterField(
            model_name='order',
            name='client_data',
            field=models.JSONField(blank=True, default=dict, help_text='Full visit/capture payload'),
        ),
    ]
